---
- hosts: localhost
  gather_facts: true
  become: yes
  tasks:
    - block:
      - name: Installing httpd for redhat os family
        yum:
          name: httpd
          state: present
      - name: start httpd for Redhat os family
        service:
          name: httpd
          state: started
      when: ansible_os_family=="RedHat"    
    - block:
      - name: Installing apache2 for Debian os family
        yum:
          name: apache2
          state: present
      - name: start apache2 for Debian os famile
        service:
          name: apache2
          state: started
      when: Ansible_os_family=="Debian"
    - debug:
        msg: "Successfully completed all tasks"

