# read variable value while playing playbook
---
- hosts: localhost
  vars:
   x: 50
   my_name: "ismail"
  vars_prompt:
  - name: user_name
    prompt: Enter your name
    private: no
  - name: password
    prompt: Enter your password
    private: yes
  gather_facts: false
  tasks:
  - debug:
     msg: "Ther username is {{user_name}} and password is {{password}}"
