---
- hosts: localhost
  vars:
   x: 50
   my_name: "ismail"
  vars_prompt:
   name: y
   prompt: Enter the y value is
   private: no
  gather_facts: false
  tasks:
  - debug:
     msg:
     - "The x value is: {{x}}"
     - "My name is : {{my_name}}"
     - "The value of y is : {{y}}"
